spring:
  cloud:
    gateway:
      default-filters:
        - name: AuthorizationHeaderFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/auth/**
        - id: wish-service
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/wish/**
        - id: product-service
          uri: lb://APPLICATION-PRODUCT
          predicates:
            - Path=/product/**
        - id: cart-service
          uri: lb://APPLICATION-CART
          predicates:
            - Path=/cart/**
        - id: order-service
          uri: lb://APPLICATION-ORDER
          predicates:
            - Path=/order/**

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: '{cipher}8141d3f392c276e31b4d3ae140a263ba959c8ed5d7b34e85e9ee8af907f6aca6'
      repositories:
        enabled: false
jwt:
  secret: '{cipher}741ae6d415c9fd35d0e94529046e30b3e16c12c704490f707a72b8db35c980f7ab32722f4f9714f042e4c06f49882da0682721a5b87b835591c66050cf0d33a573fdb06868c14f204c6ca21c726118b2c2cc72ed7c3a554fc10de3eefdccf0366abc4edfc001575f20905bb20acb8064'

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://discovery-server:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, circuitbreakers, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      resilience4j:
        circuitbreaker:
          calls: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
        registerHealthIndicator: true
    instances:
      commerce-circuit-breaker:
        base-config: default

