spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://application-user
          predicates:
            - Path=/user/**
        - id: auth-service
          uri: lb://application-user
          predicates:
            - Path=/auth/**
        - id: wish-service
          uri: lb://application-user
          predicates:
            - Path=/wish/**
        - id: product-service
          uri: lb://application-product
          predicates:
            - Path=/product/**
        - id: cart-service
          uri: lb://application-cart
          predicates:
            - Path=/cart/**
        - id: order-service
          uri: lb://application-order
          predicates:
            - Path=/order/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
