spring:
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  endpoints:
    web:
      base-path: /product/secret
      exposure:
        include: info, health, metrics, circuitbreakers, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      resilience4j:
        circuitbreaker:
          calls: true
