spring:
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    ip-address: ${EUREKA_INSTANCE_IP}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, circuitbreakers, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      resilience4j:
        circuitbreaker:
          calls: true
