spring:
  main:
    allow-bean-definition-overriding: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: '{cipher}8ce7febdef5ff085b56de3efee4e2dce9b624ec07df9cb4b71399e026ae50270291a85dc056b148ee4e270c9c5a55f63'
    password: '{cipher}9604d8050dc675605251a3f443a30216242a126b43bcc20e74e4e6e353f0c204bb048312dfe11567696495d4f936f7f3'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

eureka:
#  instance:
#    prefer-ip-address: true
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#    ip-address: ${EUREKA_INSTANCE_IP}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, circuitbreakers, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      resilience4j:
        circuitbreaker:
          calls: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      productServiceCircuitBreaker:
        base-config: default
  retry:
    instances:
      productServiceRetry:
        max-attempts: 3        # 최대 재시도 횟수
        wait-duration: 500ms   # 각 재시도 사이의 대기 시간
