spring:
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}
management:
  endpoints:
    web:
      base-path: /order/secret
      exposure:
        include: info, health, metrics, circuitbreakers, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      resilience4j:
        circuitbreaker:
          calls: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      productServiceCircuitBreaker:
        base-config: default
      cartServiceCircuitBreaker:
        base-config: default
  retry:
    instances:
      productServiceRetry:
        max-attempts: 3        # 최대 재시도 횟수
        wait-duration: 500ms   # 각 재시도 사이의 대기 시간
      cartServiceRetry:
        max-attempts: 3        # 최대 재시도 횟수
        wait-duration: 500ms   # 각 재시도 사이의 대기 시간

