spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234
      repositories:
        enabled: false
  jwt:
    secret: ecommercedasfasfwqdwfqwgggsassaffqwljkjwfklwqjfkwlqjfiowqfnkngklqjgkqwlgjlkqwfwwghqehhhhhs
  default:
    admin_id: imMaster@naver.com
    admin_pwd: 1234


  aes:
    secret: qrWkovCNhAToTFwnSMXXsy9aSfEOt9G2
  springdoc:
    default-produces-media-type: application/json;charset=UTF-8
    default-consumes-media-type: application/json;charset=UTF-8
    cache:
      disabled: true
    packages-to-scan: org.book.commerce.bookcommerce.domain
    api-docs:
      path: /swagger-ui
  datasource:
    url: jdbc:mysql://localhost:3306/whateverWithMe?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 12341234
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    web:
      exposure:
        include:"*"
